env:
  browser: true
  es2021: true
extends:
  - airbnb-base
  - eslint:recommended
  - plugin:@typescript-eslint/eslint-recommended
  - plugin:@typescript-eslint/recommended
  - plugin:solid/typescript
plugins:
  - solid
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules: {
  max-len: [
    error, {
      code: 120,
      tabWidth: 2
    }
  ],
  no-use-before-define: off,
  import/extensions: off,
  import/prefer-default-export: off,
  no-console: off,
  arrow-body-style: off,
  jsx-a11y/label-has-associated-control: off,
  no-restricted-syntax: off,
  no-shadow: off,
  no-underscore-dangle: off,
  import/no-unresolved: off,
  no-unreachable: off,
  no-continue: off,
  no-plusplus: off,
  class-methods-use-this: off,
  no-bitwise: off,
  no-undef: off,
  no-labels: off,
  no-unused-vars: off,
  '@typescript-eslint/no-unused-vars': ['warn'],
  '@typescript-eslint/no-non-null-assertion': 'off',
  '@typescript-eslint/no-explicit-any': 'off',
}

